# Generated by Django 3.1.7 on 2021-04-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-avatar.jpeg', null=True, upload_to='users/'),
        ),
    ]
